
logger:
    file: /opt/open5gs/var/log/open5gs/amf.log

sbi:
    server:
      no_tls: true
      cacert: /opt/open5gs/etc/open5gs/tls/ca.crt
      key: /opt/open5gs/etc/open5gs/tls/amf.key
      cert: /opt/open5gs/etc/open5gs/tls/amf.crt
    client:
      no_tls: true
      cacert: /opt/open5gs/etc/open5gs/tls/ca.crt
      key: /opt/open5gs/etc/open5gs/tls/amf.key
      cert: /opt/open5gs/etc/open5gs/tls/amf.crt

amf:
    sbi:
      - dev: eth0
        port: 7777
    ngap:
      - dev: eth0
    guami:
      - plmn_id:
          mcc: 999
          mnc: 70
        amf_id:
          region: 2
          set: 1
    tai:
      - plmn_id:
          mcc: 999
          mnc: 70
        tac: 1
    plmn_support:
      - plmn_id:
          mcc: 999
          mnc: 70
        s_nssai:
          - sst: 1
            sd: 0xffffff
    security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
    network_name:
        full: Open5GS
    amf_name: amf

scp:
    sbi:
      - name: scp
        port: 7777

nrf:
    sbi:
      - name: nrf
        port: 7777
      
parameter:
max:
usrsctp:
time:
  t3512:
    value: 540
