db_uri: mongodb://mongo/open5gs

logger:
    file: /opt/open5gs/var/log/open5gs/scp.log

sbi:
    server:
      no_tls: true
      cacert: /opt/open5gs/etc/open5gs/tls/ca.crt
      key: /opt/open5gs/etc/open5gs/tls/scp.key
      cert: /opt/open5gs/etc/open5gs/tls/scp.crt
    client:
      no_tls: true
      cacert: /opt/open5gs/etc/open5gs/tls/ca.crt
      key: /opt/open5gs/etc/open5gs/tls/scp.key
      cert: /opt/open5gs/etc/open5gs/tls/scp.crt

scp:
    sbi:
      - dev: eth0
        port: 7777

nrf:
    sbi:
      - name: nrf
        port: 7777

parameter:

max:
time:
